version: '3'
services:
  m2t_redis:
    container_name: m2t_redis
    build: .
    image: mail2telegram/redis:dev
    restart: always
    volumes:
      - ./conf/dev.conf:/etc/redis/redis.conf
    ports:
      - 6379:6379
    sysctls:
      net.core.somaxconn: '511'
networks:
  default:
    external:
      name: m2t
